### PR TITLE
support for (un)registering modules, incl. 3rd party ones

### PR DESCRIPTION
**Pull request by illes**

### CODE REVIEW

**Comment by simartn** [comment]
@illes, thank you for this merge request. Do you have plans for running this plugin with third party modules? I thought about something like this when implementing the plugin too, but decided not to do it until there is some need for it.
If we want to support something like this we need documentation how to write and integrate modules. Especially 3rd party ones.
There are a few other things we might need to support before adding this. I have to think a bit if there are more....

1. Not the whole plugin should produce a gap if one module takes too long for data collection. Here I was thinking of a thread pool which can be used for instantiating or collection tasks. Some threads may block and the other continue collecting values. It may be used on per module basis and also in a module for independent sub-queries (i.e. every JMX server we query).

**Comment by illes** [comment]
Once `java.d` gets merged (firehol/netdata#2663), supporting third party modules will be asked for sooner or later. In the meantime, people like me wishing to use their own modules can roll their own.

In addition to third party modules, the merge request also allows for re-using the JMX module: e.g. we could provide a `java.d/jmx.cassandra.conf` which can then be enabled by uncommenting a line in `java.d.conf`. This way we can welcome contributions for monitoring other well-known Java apps.

We can certainly delay implementing such functionality only later once the code base has matured a bit.

Using thread(pool)ing for modules (or even inside modules) sounds reasonable (this could allow even tighter integration with `Printer`) A more urgent design choice to be made/enforced is what we want to do with failing modules/charts, which should be ignorable, and which should allow java.d plugin to continue with the rest of the functionality?

**Comment by simartn** [comment]
> We can certainly delay implementing such functionality only later once the code base has matured a bit.

I do not mind implementing it now if it is well documented for an end user. I would more likely get a request to support 3rd party modules than supporting it without having it well documented.

 > In addition to third party modules, the merge request also allows for re-using the JMX module: e.g. we could provide a java.d/jmx.cassandra.conf which can then be enabled by uncommenting a line in java.d.conf. This way we can welcome contributions for monitoring other well-known Java apps.

This may be great for some modules but in my opinion not for JMX. I think we should provide only one JMX module which auto-detects well-known Java apps and charts.

> A more urgent design choice to be made/enforced is what we want to do with failing modules/charts, which should be ignorable, and which should allow java.d plugin to continue with the rest of the functionality?

You are right, we should define that. I will open an issue in the netdata issue tracker and link you to discuss it there.

I agree with all other things I did not comment.

**Comment by illes** [comment]
Added more documentation on how to create a new module and a minimal-ish `ExampleModule` (inspired by `example.chart.py`).

**Review by simartn — CHANGES_REQUESTED** [review]
Thank you for the documentation. The example plugin will be a great start for contributors. One thing I want you to mention in the doc is that if collectValues takes longer than updateEvery, all modules of the java plugin will be delayed. After that I think this is ready to be merged.

**Comment by illes** [comment]
Extended the docs. I noticed that `Plugin.cleanup()` was not called, see the attempted fix.

**Review by simartn — APPROVED** [review]

**Comment by simartn** [comment]
Thank you. Please rebase. I think this is ready to be merged.

**Pull request merged**
